name: Revisi칩n de HTML 游

# 1. Cu치ndo se activa:
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 2. Qu칠 va a hacer el robot:
jobs:
  build:
    runs-on: ubuntu-latest # Una PC virtual con Linux

    steps:
      - name: Descargar mi c칩digo
        uses: actions/checkout@v4 # El robot "clona" tu c칩digo

      - name: Validar HTML
        uses: html-validate/html-validate-action@v1 # El robot revisa el HTML
        with:
          include: 'index.html'